### ISSUE TITLE
Requirements for PNG/JPEG print

### ISSUE THREAD

**Issue by taras-chr** [star-micronics/star-cloudprnt-for-woocommerce#17]
Is there a possibility to extend this plugin to print JPG or PNG images and what exactly requirements for that images could be?

**Comment by taras-chr** [comment]
Hi @Lozrus,
We've implemented `cputil` method but there is some problem with printing of `.bin` files. The util is successfully converting png images into command files but printer doesn't print it however process going right and with no any errors. Can you suggest something? Do you need more details?
Thanks.

**Comment by Lozrus** [comment]
@taras-chr
The first points to check are:
- Make sure that your `Content-Type` header is correct. After converting the data with `cputil` it is probably `application.vnd.star.starprnt` (or whatever printer native data you are converting to). If the printer receives a GET response with a `Content-Type` that it can't support then it will not attempt to print it.
- Ensure that after converting to binary data, you are delivering it exactly byte-for-byte in your GET response. A common mistake is to treat the converted data as a string, e.g. with utf-8 encoding, but is will contain many bytes that do not map to real UTF-8 code points and so most frameworks will transform the data when doing this and trash the data. This may result in it failing to print completely, or potentially printing some garbage output.
- Check the `code` parameter of the corresponding `DELETE` request that the printer sends to the server after it uses a `GET` to retrieve the print job. Since you are using a version of the Wordpress plugin, this may actually be sent as a `GET` request, but with `delete` as a query parameter. The `code` parameter should reveal why the printer failed to print the job (e.g. unknown content-type, problems decoding the data, loo large, etc).

Also, if the printer is on the same network as your development system, then you can test your resulting binary data by using a utility like `netcat` to send if directly to your printer on port 9100. This can be helpful just to ensure that your resulting binary data is correct.
e.g.:
`cat data.bin | nc -N [printerIP] 9100`

**Comment by thegrowthproject** [comment]
hi @Lozrus 
We have successfully printed a receipt but > it only prints to half of the receipt width > any ideas on how we could fix this?

Thank you 

![IMG_3054](https://user-images.githubusercontent.com/62818526/141085861-52a97e98-6c42-4821-8e0e-b5ead254e95b.JPG)


@taras-chr

**Comment by Lozrus** [comment]
@thegrowthproject & @taras-chr 

By default, the conversion is a 1 to 1 mapping of image pixels to printer dots, and the mC-Print3x series can print 576 dots horizontally. So probably just making sure that your source image is 576 pixels wide should be enough.

Also, you can try adding options `thermal80` and `scale-to-fit` to the `cputil` command line (these should be before the `decode option`). This will let cputil know that it should target an 80mm wide thermal printer and to scale the source image to fit.

If this still doesn't work, then it may be that the printer itself has some custom print-width settings. This is unlikely - someone would have had to specifically enable these options - but you can check this by printing a self-test page (power the printer on with the FEED switch held for a few seconds), and us the "mC-Print Utility" app (from the App or Play stores) to adjust the settings.

Since it appears that your image is less than 576pixels wide, there will be upscaling, which can potentially cause visible artefacts. Also, any scaling is best avoided when printing any kind of barcode. So I recommend matching the printers native image width if possible for the best results.
